### ISSUE TITLE
HTTP 404 Not Found

### ISSUE THREAD

**Issue by DietgerBahn** [ibm-security-intelligence/visualizations#12]
Followed the readme but get a HTTP 404 Not Found when launching the URL in QRadar version 7.2.4 MR4 Patch5 IF1... any ideas are appreciated. Regards, dietger.bahn@us.ibm.com

**Comment by JasonKeirstead** [comment]
HI Dietger, I think the readme is mis-formatted.

Proper URL is https://[CONSOLE IP ADDRESS]/console/offense_visualizer/index.html

I will update the README.
