### ISSUE TITLE
Unable to view the offense

### ISSUE THREAD

**Issue by rpremk24** [ibm-security-intelligence/visualizations#13]
Hello, I hold QRadar v7.2.5. I have tried this visualizer by scp to the server but i cannot watch the neither map nor offense. Guide me if i should update the api key? If yes, pls help me on this path.

**Comment by JasonKeirstead** [comment]
HI @rpremk24 we will need more information to troubleshoot what is going on. Are there any errors in  your Firefox Javascript  console?

**Comment by JasonKeirstead** [comment]
I believe this should be fixed now - please try again.
