### ISSUE TITLE
Error in retrieveing the Asset Details. 

### ISSUE THREAD

**Issue by TejaRamachandran** [ibm-security-intelligence/visualizations#14]
Hi ChrisMeenan,

I was trying your advanced search code to retrieve asset details with help of asset saved search Id., But i was getting the run time error run time error '5'. 

But for normal log activity search it was working fine by using AQL search query. 

I think code was executing perfectly at run time error was coming.

Sub GetArielData()
    ' Create a RestClient for executing requests
    ' and set a base url that all requests will be appended to
    Dim QRadarClient As New RestClient
    Dim ServerIP As String
    Dim SecToken As String
    Dim Offset As Integer
    Dim SheetName As String
    Dim Query As String
        SheetName = Sheets("Config").Cells(3, 2).Value
    Query = Sheets("Config").Cells(4, 2).Value
        If SheetName = "Config" Then
        MsgBox ("Please select another worksheet to retrieve offenses")
        Exit Sub
    End If
    If SheetName = "" Then
        MsgBox ("Please provide a worksheet name to retrieve offenses into")
        Exit Sub
    End If
        If Sheets(SheetName) Is Nothing Then
        MsgBox SheetName & " does not exist"
        Exit Sub
    End If
        ServerIP = Sheets("Config").Cells(1, 2).Value
    SecToken = Sheets("Config").Cells(2, 2).Value
        Dim SearchID As String
    SearchID = 78
    QRadarClient.BaseUrl = "https://" + ServerIP + "api/asset_model/saved_searches"
    Dim QueryResultsStatusRequest As New RestRequest
        QueryResultsStatusRequest.BaseUrl = "https://" + ServerIP
        QueryResultsStatusRequest.Resource = "/api/asset_model/saved_searches/" + SearchID + "/results"
            QueryResultsStatusRequest.Method = httpGET
            ' Set the request format -> Sets {format} segment, content-types, and parses the response
        QueryResultsStatusRequest.Format = json
        QueryResultsStatusRequest.AddHeader "SEC", SecToken
        Set Response1 = QRadarClient.Execute(QueryResultsStatusRequest)
                'Set jsonObj = json.Parse(Respsone.Body)
        ' MsgBox (jsonObj("message"))
        If Response1.StatusCode = Ok Then
            ProcessAriel Response1, SheetName, Offset
        Else
            MsgBox Response1.Data("message")
        End If
End Sub
Public Sub ProcessAriel(ByVal Response1 As RestResponse, SheetName As String, Offset As Integer)
    If Response1.StatusCode = Ok Then
        Dim Offense As Dictionary
        Dim i, k As Integer
       Dim myStr As String
    Sheets(SheetName).UsedRange.Clear
    For i = 0 To UBound(Response1.Data("events")(1).Keys())
        Sheets(SheetName).Cells(1, i + 1).Value = Response1.Data("events")(1).Keys()(i)
    Next i
        For i = 0 To Response1.Data("events").count - 1
        For j = 0 To UBound(Response1.Data("events")(i + 1).Keys())
            Sheets(SheetName).Cells(2 + i, j + 1).Value = Response1.Data("events")(i + 1).Items()(j)
        Next j
    Next i
    End If
End Sub

The searchID 78 is asset saved searchID.
How to use this code for retrieving asset details and reference set.  

Please help me on this. 
![5](https://cloud.githubusercontent.com/assets/12483553/9256744/e660eece-420e-11e5-8d3e-66a0b4e320c2.PNG)
![6](https://cloud.githubusercontent.com/assets/12483553/9256745/e66125ba-420e-11e5-933c-4a487969792c.PNG)

**Comment by JasonKeirstead** [comment]
HI @TejaRamachandran can I request that you re-open this issue under the data-import section? Unfortunately Github does not let me move issues from one project to another.
