### ISSUE TITLE
Unable to show offences

### ISSUE THREAD

**Issue by Jcleuren** [ibm-security-intelligence/visualizations#19]
We use a Qradar SIEM v7.2.6.
Last week we attended a Qradar training, where the offence visualizer was shown. When I decided to test it on our installation, it wouldn't show any data (no map, no bubbles, etc).
When taking a closer look at the code, I found that he keeps failing at the following line with a 403 error: 
var offenses = JSON.parse(response.responseText)
I tried the following things :  
* Logging in with the default admin account with no success
* Creating a auth token and putting it in the visualizer.js

**Comment by JasonKeirstead** [comment]
Thanks for the report - I will have a look at this.

**Comment by JasonKeirstead** [comment]
This should be fixed now
