### ISSUE TITLE
Installing not on QRadar Console

### ISSUE THREAD

**Issue by RyPeck** [ibm-security-intelligence/visualizations#9]
Is it possible to not install this on the QRadar console? How would the setup instructions change?

Reluctant to make unsupported changes to the console.

**Comment by RyPeck** [comment]
@JasonKeirstead, saw the update for 7.2.5 that "Allowed origins whitelist - You can now manage a list of origins that have permissions to make cross-domain API calls to your server." - https://www.ibm.com/developerworks/community/forums/html/topic?id=ed9ba39b-59f0-47a1-aab9-f133322c57d3

I'm guessing that this means CORS has been added?

**Comment by K-Moss** [comment]
Hi RyPeck,  Yes, the allowed origins whitelist is to support CORS. You can find more documentation on it here: http://www-01.ibm.com/support/knowledgecenter/SS42VS_7.2.5/com.ibm.qradar.doc_7.2.5/c_rest_api_cors.html%23concept_uj4_q4k_qr

**Comment by RyPeck** [comment]
@K-Moss thanks! Do you guys have any plans to modify this repo to support that?

**Comment by K-Moss** [comment]
Feel free to send a pull request for changes you feel the samples should include.  There's no plan currently to update these samples in the near future.

**Comment by JasonKeirstead** [comment]
Ryan, now that 7.2.5 has been released, I will likely update the visualization samples soon to include CORS support as it has been asked for multiple times. I'll close this issue once it's done.

Thanks,

**Comment by RyPeck** [comment]
@JasonKeirstead sounds great - I will definitely test once running 7.2.5 (soon hopefully).

**Comment by JasonKeirstead** [comment]
Closing this as CORS is now supported.
